### ISSUE TITLE
No RSS feed

### ISSUE THREAD

**Issue by benjaminoakes** [estrattonbailey/Nominal#2]
Hey Eric!  I used to subscribe to http://blog.ericbailey.co/feed, but it broke -- probably around the time you changed domains or to using Nominal.  Just a heads up.  I couldn't find another RSS feed in the new theme.

**Comment by estrattonbailey** [comment]
Hey Ben! That must have been around the time I took my Jekyll site down and started sending traffic to my [tumblr](estrattonbailey.tumblr.com). I imagine Nominal would work fine if it was still running, but not sure. It's a pretty basic theme! :P
